import express from "express";
import dotenv from "dotenv";
import axios from "axios";
import OpenAI from "openai";

dotenv.config();

const app = express();
app.use(express.json({ limit: "50mb" }));

const PORT = process.env.PORT || 3000;
const TOKEN = process.env.TG_BOT_TOKEN;
const WEBHOOK_URL = process.env.WEBHOOK_URL;

const TELEGRAM_API = `https://api.telegram.org/bot${TOKEN}`;

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const userPhotos = new Map();

const IMAGE_PROMPT = `
You are a specialized AI fashion image generator focused on realistic Philippine streetwear OOTD photography.

When 2 images are provided:
- Image 1 = outfit reference only
- Image 2 = subject/person reference only

Never mix the identity from Image 1 with the person from Image 2.

Use Image 1 only for:
- clothing design
- garment structure
- color
- fabric
- silhouette
- texture
- styling
- fit
- stitching/details

Use Image 2 only for:
- exact face identity
- hairstyle
- skin tone
- body proportions
- facial structure
- natural appearance

Preserve the exact identity from Image 2.

Generate exactly ONE image only.

Format:
- vertical 9:16
- realistic smartphone photo
- raw unfiltered look
- 4K quality
- candid streetwear OOTD vibe

Allowed Philippine locations:
- sidewalks
- MRT/LRT stations
- stairways
- footbridges
- local shops
- sari-sari stores
- walkways
- concrete gates
- public waiting areas
- building entrances
- curbside spots
- terminal areas
- outdoor stairs
- quiet street corners

Lighting:
- natural Philippine daylight
- humid tropical atmosphere
- mild shadows
- realistic smartphone exposure

Final goal:
A highly realistic Philippine streetwear OOTD image featuring the exact person from Image 2 wearing the exact outfit from Image 1, captured like a casual smartphone photo taken by a friend in a believable everyday Philippine setting.
`;

app.get("/", (req, res) => {
  res.send("Telegram OOTD Bot Running");
});

app.get("/set-webhook", async (req, res) => {
  try {
    const url = `${WEBHOOK_URL}/webhook`;

    const response = await axios.get(`${TELEGRAM_API}/setWebhook?url=${url}`);

    res.json(response.data);
  } catch (error) {
    console.error(error.response?.data || error.message);
    res.status(500).json({
      error: error.message,
    });
  }
});

app.post("/webhook", async (req, res) => {
  try {
    const message = req.body.message;

    if (!message) {
      return res.sendStatus(200);
    }

    const chatId = message.chat.id;

    if (message.text === "/start") {
      await sendMessage(
        chatId,
        `Send:\n\n1 photo = subject only\n2 photos = outfit + subject\n\nPhoto Order:\n1st photo = outfit\n2nd photo = person`,
      );

      return res.sendStatus(200);
    }

    if (message.photo) {
      const photos = userPhotos.get(chatId) || [];

      const fileId = message.photo[message.photo.length - 1].file_id;

      photos.push(fileId);
      userPhotos.set(chatId, photos);

      await sendMessage(chatId, `Photo received (${photos.length}/2)`);

      if (photos.length === 2) {
        await sendMessage(
          chatId,
          "Generating realistic Philippine OOTD image...",
        );

        const imageUrls = [];

        for (const fileId of photos) {
          const fileUrl = await getTelegramFileURL(fileId);
          imageUrls.push(fileUrl);
        }

        const generatedImage = await generateOOTDImage(imageUrls);

        await sendPhoto(chatId, generatedImage);

        userPhotos.delete(chatId);
      }
    }

    res.sendStatus(200);
  } catch (error) {
    console.error(error.response?.data || error.message);
    res.sendStatus(500);
  }
});

async function getTelegramFileURL(fileId) {
  const response = await axios.get(`${TELEGRAM_API}/getFile?file_id=${fileId}`);

  const filePath = response.data.result.file_path;

  return `https://api.telegram.org/file/bot${TOKEN}/${filePath}`;
}

async function generateOOTDImage(imageUrls) {
  try {
    const result = await openai.images.generate({
      model: "gpt-image-1",
      prompt: IMAGE_PROMPT,
      size: "1024x1792",
      image: imageUrls,
    });

    const imageBase64 = result.data[0].b64_json;

    return `data:image/png;base64,${imageBase64}`;
  } catch (error) {
    console.error(error);
    throw error;
  }
}

async function sendMessage(chatId, text) {
  await axios.post(`${TELEGRAM_API}/sendMessage`, {
    chat_id: chatId,
    text,
  });
}

async function sendPhoto(chatId, photoBase64) {
  await axios.post(`${TELEGRAM_API}/sendPhoto`, {
    chat_id: chatId,
    photo: photoBase64,
    caption: "Generated by OOTD AI Bot",
  });
}

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
